/**:
  ros__parameters:
    type: 'mcbl3006'
    device: '/dev/motor_y'
    baud: 19200
    timeout: 0.2
    update_period_ms: 100
    increments_per_length_unit: 645161
    rpm_per_velocity_unit: 14100
    nominal_rpm: 4890
