/**:
  ros__parameters:
    type: 'mcbl3006'
    device: '/dev/motor_y'
    baud: 19200
    timeout: 0.2
    update_period_ms: 100
    # 3000 increments per rev (see datasheet)
    increments_per_rev: 3000
    increments_per_length_unit: 645161
    # max rpm 3000
    nominal_rpm: 4890
