/**:
  ros__parameters:
    type: 'mcbl2805'
    device: '/dev/motor_x'
    baud: 19200
    timeout: 0.2
    update_period_ms: 100
    # 1000 increments per rev (see datasheet)
    increments_per_rev: 1000
    increments_per_length_unit: 591125
    # max rpm 5500
    nominal_rpm: 7700
